### ISSUE TITLE
CRUD for Trip

### ISSUE THREAD

**Issue by tuanhuynh18** [tuanhuynh18/monarch#1]
CREATE Trip
Input:
{
  city: city_name,
  total_budget: budget_here,
  start_date: date_here (format mm/dd/yyyy),
  end_date: date_here (format mm/dd/yyyy),
}
Output:
http_status code: 200 (success), 500 (server error), etc.
if success:
{
  trip_id: id_here
}
if error:
{
  error_message: error_message_here_if_any
}

DELETE Trip
Input:
{
  trip_id: id_here
}

GET list of trip
Output: list of trip added
{
  trips: [
   {
     trip_id: id_here
     city: city_name,
     total_budget: budget_here,
     start_date: date_here (format mm/dd/yyyy),
     end_date: date_here (format mm/dd/yyyy),
   }, { ... }, {...}
 ]
}

GET trip detail
Input:
{
  trip_id: id_here
}
Output:
{
  places: [
   {
    place_id: id_here
     place_name: place_name_here,
     longtitute: longtitude_here,
     latitude: lattitude_here,
     estimated_cost: cost_here
   }, {...}, {....}
 ]
}

**Comment by lincolnanders5** [comment]
Most of this looks like it's covered already. Check the Postman collection in the backend branch for details.
